version: '3.8'

services:
  kafkaclient:
    container_name: kafkaclient
    build: .
    volumes:
      - ./Apache-Kafka-Project:/app/Apache-Kafka-Project
      - ./logs:/app/logs
    ports:
      - 9092:9092
    networks:
      - app-network

  kafkabackend:
    container_name: kafkabackend
    image: node:18-alpine
    command: sh -c "sleep 40 && npm install && node index.js"
    depends_on:
      - kafkaclient
    working_dir: /app
    volumes:
      - ./Starbucks-stock-backend:/app
    environment:
      - KAFKA_HOST=kafkaclient
      - KAFKA_PORT=9092
    ports:
      - 3001:3001
    networks:
      - app-network

  kafkafrontend:
    container_name: kafkafrontend
    image: node:18-alpine
    command: sh -c "sleep 40 &&  npm install && npm run dev"
    depends_on:
      - kafkaclient
      - kafkabackend
    working_dir: /app 
    volumes:
      - ./Starbucks-stock-frontend:/app
    environment:
      - NEXT_PUBLIC_APIHOST=kafkabackend
      - NEXT_PUBLIC_APIPORT=3001
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge